codecov:
  require_ci_to_pass: yes # Require CI build to pass before uploading coverage reports

coverage:
  precision: 2 # Set the precision for coverage percentages

ignore:
  - "*/tests/*" # Ignore test files and directories

comment:
  layout: "header, diff, sunburst, changes, tree" # Specify which sections of the comment to include
  behavior: default # Comment behavior (you can customize this)

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
