codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 1% # You can adjust the threshold value
        paths:
          - "clic/src/*"

comment:
  layout: "header, diff, sunburst, changes, tree"
  behavior: default

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no